# Generated by Django 4.2.2 on 2023-06-14 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campass', '0002_alter_house_options_amenities'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('rate', models.DecimalField(decimal_places=1, max_digits=2)),
            ],
        ),
    ]
