# Generated by Django 4.2.2 on 2023-11-25 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campass', '0003_map_alter_contact_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='description',
            new_name='Agency',
        ),
        migrations.RenameField(
            model_name='house',
            old_name='area',
            new_name='bathrooms',
        ),
        migrations.RenameField(
            model_name='house',
            old_name='baths',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='facilities',
            name='description',
        ),
        migrations.RemoveField(
            model_name='house',
            name='address',
        ),
        migrations.RemoveField(
            model_name='house',
            name='beds',
        ),
        migrations.RemoveField(
            model_name='house',
            name='description',
        ),
    ]
