# Generated by Django 4.2.2 on 2023-06-16 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campass', '0005_facilities_alter_mover_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='image',
            field=models.ImageField(default='agent.png', upload_to='houses'),
        ),
        migrations.AddField(
            model_name='facilities',
            name='image',
            field=models.ImageField(default='agent.png', upload_to='houses'),
        ),
    ]
