# Generated by Django 4.2.2 on 2023-06-19 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campass', '0006_agent_image_facilities_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='mover',
            name='image',
            field=models.ImageField(default='agent.png', upload_to='houses'),
        ),
        migrations.AlterField(
            model_name='mover',
            name='rate',
            field=models.FloatField(),
        ),
    ]
