# Generated by Django 4.2.2 on 2023-06-19 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campass', '0007_mover_image_alter_mover_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='image',
            field=models.ImageField(default='houses/agent.png', upload_to='houses'),
        ),
        migrations.AlterField(
            model_name='facilities',
            name='image',
            field=models.ImageField(default='houses/agent.png', upload_to='houses'),
        ),
        migrations.AlterField(
            model_name='mover',
            name='image',
            field=models.ImageField(default='houses/agent.png', upload_to='houses'),
        ),
    ]
