# Generated by Django 4.2.2 on 2023-06-20 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campass', '0008_alter_agent_image_alter_facilities_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=500)),
                ('message', models.CharField(max_length=500)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
